// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfrhynjlxcadauyssqcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcmh5bmpseGNhZGF1eXNzcWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzODg1MTIsImV4cCI6MjA2Nzk2NDUxMn0.J4UdaVT84sqeNiwYuAlgOkXggPtOK5sPAWtt3-AB4LE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});